function top20 = top20()
top20 = {
    'England'
    'France'
    'Scotland'
    'Ireland'
    'Wales'
    'Italy'
    'New Zealand'
    'Tonga'
    'Samoa'
    'South Africa'
    'Australia'
    'Fiji'
    'Canada'
    'Argentina'
    'Japan'
    'United States of America'
    'Georgia'
    'Romania'
    'Spain'
    'Russia'};